### ISSUE TITLE
A syntactically correct space causes test failures for includes

### ISSUE THREAD

**Issue by snychka** [pluralsight-projects/NodeExpress-BankingPortal#2]
@tjbell sorry, this is a work in progress

- thought initially just a regext thing.  Not the case
- ejs doesn't compile if you have `include (`, so a space before the parentheses.

that seems crazy odd.  I'll DM you tomorrow, as I hope you have more insight.  If not, I'll need more time to investigate what be up!

```
> npm run test:module1

> nodeexpress-untitled@0.0.1 test:module1 /Users/anonymy/GitRepos/NodeExpress-BankingPortal
> NODE_ENV=test mocha --exit './test/module1/*.spec.js' || true



  Default Route
    ✓ should contain the index route @app-get-index-route

  Server created with app.listen
    ✓ should contain app.listen @app-listen-console-log

  Require `fs` and `path` built-ins
    ✓ should contain requires @app-require-built-ins

  Require Express and Create `app` const
    ✓ require express and create app const @app-require-express-const-app

  View engine and directory
    ✓ should set view engine and directory @app-set-views-directory-engine

  Static Directory
    ✓ should set express static directory @app-use-express-static

  `index.ejs` exists
    ✓ `index.ejs` should exist  @index-ejs-create-view-file

  Create `index` view
Error: Could not find the include file "(&#34;header&#34;);"
    at getIncludePath (/Users/anonymy/GitRepos/NodeExpress-BankingPortal/node_modules/ejs/lib/ejs.js:162:13)
    at includeSource (/Users/anonymy/GitRepos/NodeExpress-BankingPortal/node_modules/ejs/lib/ejs.js:306:17)
    at /Users/anonymy/GitRepos/NodeExpress-BankingPortal/node_modules/ejs/lib/ejs.js:702:26
    at Array.forEach (<anonymous>)
    at Template.generateSource (/Users/anonymy/GitRepos/NodeExpress-BankingPortal/node_modules/ejs/lib/ejs.js:678:15)
    at Template.compile (/Users/anonymy/GitRepos/NodeExpress-BankingPortal/node_modules/ejs/lib/ejs.js:557:12)
    at Object.compile (/Users/anonymy/GitRepos/NodeExpress-BankingPortal/node_modules/ejs/lib/ejs.js:389:16)
    at Context.it (/Users/anonymy/GitRepos/NodeExpress-BankingPortal/test/module1/index-ejs-create-view.spec.js:10:11)
    at callFn (/Users/anonymy/GitRepos/NodeExpress-BankingPortal/node_modules/mocha/lib/runnable.js:383:21)
    at Test.Runnable.run (/Users/anonymy/GitRepos/NodeExpress-BankingPortal/node_modules/mocha/lib/runnable.js:375:7)
    at Runner.runTest (/Users/anonymy/GitRepos/NodeExpress-BankingPortal/node_modules/mocha/lib/runner.js:446:10)
    at /Users/anonymy/GitRepos/NodeExpress-BankingPortal/node_modules/mocha/lib/runner.js:564:12
    at next (/Users/anonymy/GitRepos/NodeExpress-BankingPortal/node_modules/mocha/lib/runner.js:360:14)
    at /Users/anonymy/GitRepos/NodeExpress-BankingPortal/node_modules/mocha/lib/runner.js:370:7
    at next (/Users/anonymy/GitRepos/NodeExpress-BankingPortal/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/Users/anonymy/GitRepos/NodeExpress-BankingPortal/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
    1) should create the index view @index-ejs-create-view


  7 passing (49ms)
  1 failing

  1) Create `index` view
       should create the index view @index-ejs-create-view:
     AssertionError:  Error compiling index.ejs
      at Context.it (test/module1/index-ejs-create-view.spec.js:15:7)




user ~/GitRepos/NodeExpress-BankingPortal
> head -1 src/views/index.ejs  
<%- include ("header");  %>

user ~/GitRepos/NodeExpress-BankingPortal
> head -17 test/module1/index-ejs-create-view.spec.js | tail -1
    assert(/<%-\s+include\(('|")header(\.ejs)?('|")\)(;)?\s*%>/.test(file), 'Have you included the `header` view.');

user ~/GitRepos/NodeExpress-BankingPortal
> 
```

**Comment by snychka** [comment]
Seems like `include ('header)` is wrong, as it gets confused between that and `include header`.

There may still be some issues, but thinking now that at least helps as it's an ejs "feature".  Still not clear why when you run it, though, (so, via `npm start` which invokes `nodemon`) the include works when there's that odd space.

sigh.  'nuf for tonight

**Comment by tjbell** [comment]
`ejs` has two different style includes: [ejs docs](https://github.com/mde/ejs#includes).
Because the space was there is was more than likely interpreting it as an include preprocessor directive (<% include header %>). As for why it worked via `npm start`. Node was less strict about the space than the `ejs` compiler which is run on each file when testing.
