### ISSUE TITLE
Module 1 test fails on one type of include format

### ISSUE THREAD

**Issue by snychka** [pluralsight-projects/NodeExpress-BankingPortal#3]
The type of include without parentheses, `<%- include header %>`, fails on `npm run test:module1`

- test/module1/index-ejs-create-view.spec.js:15:7

---

**full run of failure:**

```
user ~/GitRepos/NodeExpress-BankingPortal
> npm run test:module1

> nodeexpress-bankingportal@0.0.1 test:module1 /Users/anonymy/GitRepos/NodeExpress-BankingPortal
> cross-env NODE_ENV=test mocha --exit './test/module1/*.spec.js' || true



  Default Route
    ✓ should contain the index route @app-get-index-route

  Server created with app.listen
    ✓ should contain app.listen @app-listen-console-log

  Require `fs` and `path` built-ins
    ✓ should contain requires @app-require-built-ins

  Require Express and Create `app` const
    ✓ require express and create app const @app-require-express-const-app

  View engine and directory
    ✓ should set view engine and directory @app-set-views-directory-engine

  Static Directory
    ✓ should set express static directory @app-use-express-static

  `index.ejs` exists
    ✓ `index.ejs` should exist  @index-ejs-create-view-file

  Create `index` view
Error: Could not find the include file "header"
    at getIncludePath (/Users/anonymy/GitRepos/NodeExpress-BankingPortal/node_modules/ejs/lib/ejs.js:162:13)
    at includeSource (/Users/anonymy/GitRepos/NodeExpress-BankingPortal/node_modules/ejs/lib/ejs.js:306:17)
    at /Users/anonymy/GitRepos/NodeExpress-BankingPortal/node_modules/ejs/lib/ejs.js:702:26
    at Array.forEach (<anonymous>)
    at Template.generateSource (/Users/anonymy/GitRepos/NodeExpress-BankingPortal/node_modules/ejs/lib/ejs.js:678:15)
    at Template.compile (/Users/anonymy/GitRepos/NodeExpress-BankingPortal/node_modules/ejs/lib/ejs.js:557:12)
    at Object.compile (/Users/anonymy/GitRepos/NodeExpress-BankingPortal/node_modules/ejs/lib/ejs.js:389:16)
    at Context.it (/Users/anonymy/GitRepos/NodeExpress-BankingPortal/test/module1/index-ejs-create-view.spec.js:10:11)
    at callFn (/Users/anonymy/GitRepos/NodeExpress-BankingPortal/node_modules/mocha/lib/runnable.js:383:21)
    at Test.Runnable.run (/Users/anonymy/GitRepos/NodeExpress-BankingPortal/node_modules/mocha/lib/runnable.js:375:7)
    at Runner.runTest (/Users/anonymy/GitRepos/NodeExpress-BankingPortal/node_modules/mocha/lib/runner.js:446:10)
    at /Users/anonymy/GitRepos/NodeExpress-BankingPortal/node_modules/mocha/lib/runner.js:564:12
    at next (/Users/anonymy/GitRepos/NodeExpress-BankingPortal/node_modules/mocha/lib/runner.js:360:14)
    at /Users/anonymy/GitRepos/NodeExpress-BankingPortal/node_modules/mocha/lib/runner.js:370:7
    at next (/Users/anonymy/GitRepos/NodeExpress-BankingPortal/node_modules/mocha/lib/runner.js:294:14)
    at Immediate._onImmediate (/Users/anonymy/GitRepos/NodeExpress-BankingPortal/node_modules/mocha/lib/runner.js:338:5)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
    1) should create the index view @index-ejs-create-view


  7 passing (50ms)
  1 failing

  1) Create `index` view
       should create the index view @index-ejs-create-view:
     AssertionError:  Error compiling index.ejs
      at Context.it (test/module1/index-ejs-create-view.spec.js:15:7)




user ~/GitRepos/NodeExpress-BankingPortal
> head -1 src/views/index.ejs 
<%- include header %>

user ~/GitRepos/NodeExpress-BankingPortal
> 
```

**likely fix:** (test/module1/index-ejs-create-view.spec.js)

```js
const fs = require('fs');
const path = require('path');
const ejs = require('ejs');

describe('Create `index` view', () => {
  it('should create the index view @index-ejs-create-view', () => {
    let file;
    try {
      file = fs.readFileSync(path.join(process.cwd(), 'src/views/index.ejs'), 'utf8');
      // TELL ejs where the include file is
      ejs.compile(file, {
        filename: 'src/views/index.ejs'
      });
    } catch (err) {
      console.log(err);
      assert(err.code !== 'ENOENT', 'The `index.ejs` view file does not exist.');
      const errorMessage = err.message.substring(0, err.message.indexOf('compiling ejs'));
      assert(err.message.indexOf('compiling ejs') < -1, ` ${errorMessage}Error compiling index.ejs`);
    }
    // have regex accept this type of header
    assert(
      (/<%-\s+include\(('|")header(\.ejs)?('|")\)(;)?\s*%>/.test(file) ||
      /<%-\s+include\s+header(\.ejs)?\s*%>/.test(file)),
      'Have you included the `header` view?');
    assert(/<div\s+class\s*=\s*("|'|\s*)container(\s*|"|')>/.test(file), 'The `div` with a class of `container` can not be found.');
    assert(/<%=\s*title\s*%>/.test(file), 'The `title` variable seems to be missing.');
    assert(/<a\s+href=('|")?\/profile('|")?>\s*(P|p)rofile\s*<\/a>/.test(file), 'The `profile` link seems to be missing.');
    assert(/<a\s+href=('|")?(\/services)?\/transfer('|")?>\s*(T|t)ransfer\s*<\/a>/.test(file), 'The `transfer` link seems to be missing.');
    assert(/<%-\s+include\(('|")footer(\.ejs)?('|")\)(;)?\s*%>/.test(file), 'Have you included the `footer` view?');
  });
});
```

- I'm uncertain why this is only needed for this type of include
- @tjbell , can you have a gander, and make sure this all makes sense?
- I'm fine with making a PR to update all the includes once you confirm the issue and a fix.  Just let me know.

**Comment by tjbell** [comment]
I suspect it is because of a difference in the way paths are being handled. Thank you for the fix, I will go ahead and implement that ASAP.
